spring:
  application:
    name: file-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rag
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
minio:
  url: "http://localhost:9000"
  access-key: "${MINIO_ACCESS_KEY}"
  secret-key: "${MINIO_SECRET_KEY}"
  bucket: "files"
server:
  port: 8082
